### ISSUE TITLE
Fails to start from uberjar

### ISSUE THREAD

**Issue by KSanyi** [mvysny/vaadin-boot-example-maven#1]
When I try to run it using the uberjar it fails with this:

```
500
java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.StaticFileHandler.serveStaticResource(jakarta.servlet.http.HttpServletRequest, jakarta.servlet.http.HttpServletResponse)" because "this.staticFileHandler" is null
com.vaadin.flow.server.VaadinServlet-34b7bfc0
java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.StaticFileHandler.serveStaticResource(jakarta.servlet.http.HttpServletRequest, jakarta.servlet.http.HttpServletResponse)" because "this.staticFileHandler" is null

java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.StaticFileHandler.serveStaticResource(jakarta.servlet.http.HttpServletRequest, jakarta.servlet.http.HttpServletResponse)" because "this.staticFileHandler" is null
	at com.vaadin.flow.server.VaadinServlet.serveStaticOrWebJarRequest(VaadinServlet.java:431)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:386)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1382)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1304)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by mvysny** [comment]
Excellent catch, thank you. The problem is that the `LookupServletContainerInitializer` class is not picked up and activated by Jetty's classpath scanning mechanism, which means that the `Lookup` is not initialized, which means that `VaadinServlet.init()` exits prematurely and doesn't fill in `staticFileHandler`. You can read more on the topic here: https://mvysny.github.io/vaadin-lookup-vs-instantiator/

The question is why Jetty's class autodiscovery works with zip distribution but not with the uberjar distribution. The file `com.vaadin.flow.server.startup.LookupServletContainerInitializer.class` exists in the uberjar, and also the file `META-INF/services/jakarta.servlet.ServletContainerInitializer` exists in the uberjar.

We may need a Jetty expert opinion here. However, the uberjar format suffers from multiple disadvantages and I'd be leaning towards its removal.

**Comment by mvysny** [comment]
Interesting read: https://stackoverflow.com/questions/63517432/cant-get-jetty-to-scan-for-annotated-classes-in-fat-jar

We could try the `QuickStartWebApp` approach. Will be evaluated at https://github.com/mvysny/vaadin-boot/issues/11

**Comment by KSanyi** [comment]
If you remove the uberjar format then how is it possible to simply run an app with embedded jetty? All my apps are run on embedded jetty with Vaadin. And I don't want to use Spring or any frameworks.

**Comment by mvysny** [comment]
You can always use the 'zip' format as a fallback. If you notice, a `vaadin-boot-example-maven-1.0-SNAPSHOT-zip.zip` file is produced by Maven build as well. Simply unzip the file and run `run.bat`.

**Comment by KSanyi** [comment]
I'm running my apps on heroku where I need to package in jar format.

**Comment by mvysny** [comment]
I wonder whether the following `Procfile` would work:

```
web: unzip *.zip && ./run
```

**Comment by KSanyi** [comment]
Thank you, I could manage to work with this Procfile on heroku

**Comment by mvysny** [comment]
Perfect, thank you for letting me know.

Jetty class auto-discovery doesn't work with uberjar, which is a fundamental limitation. QuickStartApp would solve this, but it has other limitations: it needs to be generated from a running app. It might be generated by the Jetty Maven plugin but there are issues with it at the moment. More info here: https://github.com/mvysny/vaadin-boot/issues/11 . So, the solution is not perfect.

To sum it up:

1. The QuickStart solution is not perfect
2. uberjar works by unpacking all jars then packing it back into one jar. The fundamental limitation is that if multiple jars introduce the same file (e.g. `META-INF/MANIFEST.MF` or service loader stuff), they will overwrite each other files and some random jar would win, leading to unreproducible builds. That is not a sound strategy.
3. The Gradle example project never introduced support for uberjar and no-one missed it.

That leads me to the conclusion to remove the support for uberjar. If need be, in the future, we could create a jar-with-dependencies, akin to what Spring Boot does: dependency jars are packed into another jar file with a small loader class, which unpacks jars, creates an URLClassLoader and runs the main method.
